# Generated by Django 4.0.6 on 2022-08-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('reg_num', models.CharField(max_length=25)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
